# Generated by Django 5.0.4 on 2024-04-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ_osoba",
                    models.CharField(
                        choices=[("EMP", "Employee"), ("CUS", "Customer")], max_length=3
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                ("birth_date", models.DateField(verbose_name="Birth date")),
                (
                    "Addressstreet",
                    models.CharField(max_length=50, verbose_name="Street"),
                ),
                ("Addressnumber", models.IntegerField(verbose_name="Number")),
                ("Addresscity", models.CharField(max_length=40, verbose_name="City")),
                (
                    "Addresspostal_code",
                    models.CharField(max_length=6, verbose_name="Postal code"),
                ),
                ("phone_number", models.CharField(max_length=20, verbose_name="Phone")),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_position",
                    models.CharField(
                        choices=[
                            ("MAN", "Manager"),
                            ("ACC", "Accountant"),
                            ("TEC", "Technician"),
                            ("WHM", "Warehouseman"),
                        ],
                        max_length=3,
                        verbose_name="Job position",
                    ),
                ),
                (
                    "person_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "Ship addressstreet",
                    models.CharField(max_length=50, verbose_name="Ship address"),
                ),
                ("Ship addressnumber", models.IntegerField(verbose_name="Number")),
                (
                    "Ship addresscity",
                    models.CharField(max_length=40, verbose_name="City"),
                ),
                (
                    "Ship addresspostal_code",
                    models.CharField(max_length=6, verbose_name="Postal code"),
                ),
                (
                    "person_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
    ]
